apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finalproject
  namespace: argocd
spec:
  destination:
    namespace: project
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: testweb
    repoURL: https://kirilllka1993.github.io/finalproject/
    targetRevision: 1.0.0+testweb-1.1.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true