apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.cred.name }}
  namespace: {{ .Values.namespace }}
data:
  username: {{ .Values.cred.username }}
  password: {{ .Values.cred.password }}
