apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "{{ .Values.deployment.actuator.port }}"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.deployment.port }}
      targetPort: {{ .Values.deployment.port }}
    - name: http-actuator
      protocol: TCP
      port: {{ .Values.deployment.actuator.port }}
      targetPort: {{ .Values.deployment.actuator.port }}
