name: Helm

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v4
      - name: Helm Installation
        uses: azure/setup-helm@v4
        with:
          version: v3.13.3
      - name: Helm Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: Kirilllka1993/finalchartproject
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: charts
      - name: Helm Package
        run: helm package my-chart --version "0.1.0+$(git rev-parse --short "$GITHUB_SHA")" -d helm-chart-repository
      - name: Helm Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "kirilllka1993@gmail.com"
          git config --global user.name "Kirill"
          CHART_PACKAGE_NAME="my-chart-0.1.0+$(git rev-parse --short "$GITHUB_SHA").tgz"
          cd charts
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin main