name: Helm

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Helm Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: Kirilllka1993/finalchartproject
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: charts
      - name: Helm Package
        run: helm package helm-charts --version "0.1.0+$(git rev-parse --short "$GITHUB_SHA")" -d charts
      - name: Helm Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd charts
          ls
          git config --global user.email "kirilllka1993@gmail.com"
          git config --global user.name "Kirill"
          CHART_PACKAGE_NAME="charts/testweb-0.1.0.tgz"
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin main