name: Helm

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Helm Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: Kirilllka1993/finalproject
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          ref: helm-branch
          path: charts
      - name: Helm Package
        run: helm package helm-charts --version "0.1.0+$(git rev-parse --short "$GITHUB_SHA")" -d charts
      - name: Helm Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd charts
          ls
          git config --global user.email "kirilllka1993@gmail.com"
          git config --global user.name "Kirill"
          CHART_PACKAGE_NAME="testweb-0.1.0+$(git rev-parse --short "$GITHUB_SHA").tgz"
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin helm-branch

      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Helm Installation
        uses: azure/setup-helm@v4
        with:
          version: v3.13.3
          repository: Kirilllka1993/finalproject
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: helm-branch
      - name: Update Index
        run: |
          
          helm repo index .
          git config --global user.email "kirilllka1993@gmail.com"
          git config --global user.name "Kirill"
          git checkout helm-branch
          git add index.yaml
          git commit -m "Update chart index"
          git push origin helm-branch