name: release-chart
on:
  push:
    branches: [ "main" ]

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: Kirilllka1993/finalproject@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: helm-charts
          charts_url: https://kirilllka1993.github.io/finalchartproject
          repository: Kirilllka1993/finalchartproject
          branch: main